x,y=input("enter a value:").split()
print("no of boys:,x")
print("no of boys:,y")
print(x,y)
x,y,z=input("enter 3 values:").split('*')
print(x)
print(y)
print(z)
x,y,z=input("enter 3 values:").split('?')
print(x)
print(y)
print(z)
